<?php
/**
 * BrandTemplateApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Integrations\Canva\SDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Integrations\Canva\SDK\ApiException;
use Integrations\Canva\SDK\Configuration;
use Integrations\Canva\SDK\HeaderSelector;
use Integrations\Canva\SDK\ObjectSerializer;

/**
 * BrandTemplateApi Class Doc Comment
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandTemplateApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getBrandTemplate' => [
            'application/json',
        ],
        'getBrandTemplateDataset' => [
            'application/json',
        ],
        'listBrandTemplates' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getBrandTemplate
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplate'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Integrations\Canva\SDK\Model\GetBrandTemplateResponse|\Integrations\Canva\SDK\Model\Error
     */
    public function getBrandTemplate($brand_template_id, string $contentType = self::contentTypes['getBrandTemplate'][0])
    {
        list($response) = $this->getBrandTemplateWithHttpInfo($brand_template_id, $contentType);
        return $response;
    }

    /**
     * Operation getBrandTemplateWithHttpInfo
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplate'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Integrations\Canva\SDK\Model\GetBrandTemplateResponse|\Integrations\Canva\SDK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBrandTemplateWithHttpInfo($brand_template_id, string $contentType = self::contentTypes['getBrandTemplate'][0])
    {
        $request = $this->getBrandTemplateRequest($brand_template_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Integrations\Canva\SDK\Model\GetBrandTemplateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\GetBrandTemplateResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\GetBrandTemplateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\Error' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Integrations\Canva\SDK\Model\GetBrandTemplateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\GetBrandTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBrandTemplateAsync
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandTemplateAsync($brand_template_id, string $contentType = self::contentTypes['getBrandTemplate'][0])
    {
        return $this->getBrandTemplateAsyncWithHttpInfo($brand_template_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBrandTemplateAsyncWithHttpInfo
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandTemplateAsyncWithHttpInfo($brand_template_id, string $contentType = self::contentTypes['getBrandTemplate'][0])
    {
        $returnType = '\Integrations\Canva\SDK\Model\GetBrandTemplateResponse';
        $request = $this->getBrandTemplateRequest($brand_template_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBrandTemplate'
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBrandTemplateRequest($brand_template_id, string $contentType = self::contentTypes['getBrandTemplate'][0])
    {

        // verify the required parameter 'brand_template_id' is set
        if ($brand_template_id === null || (is_array($brand_template_id) && count($brand_template_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand_template_id when calling getBrandTemplate'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]{1,50}$/", $brand_template_id)) {
            throw new \InvalidArgumentException("invalid value for \"brand_template_id\" when calling BrandTemplateApi.getBrandTemplate, must conform to the pattern /^[a-zA-Z0-9_-]{1,50}$/.");
        }
        

        $resourcePath = '/v1/brand-templates/{brandTemplateId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($brand_template_id !== null) {
            $resourcePath = str_replace(
                '{' . 'brandTemplateId' . '}',
                ObjectSerializer::toPathValue($brand_template_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBrandTemplateDataset
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplateDataset'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse|\Integrations\Canva\SDK\Model\Error
     */
    public function getBrandTemplateDataset($brand_template_id, string $contentType = self::contentTypes['getBrandTemplateDataset'][0])
    {
        list($response) = $this->getBrandTemplateDatasetWithHttpInfo($brand_template_id, $contentType);
        return $response;
    }

    /**
     * Operation getBrandTemplateDatasetWithHttpInfo
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplateDataset'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse|\Integrations\Canva\SDK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBrandTemplateDatasetWithHttpInfo($brand_template_id, string $contentType = self::contentTypes['getBrandTemplateDataset'][0])
    {
        $request = $this->getBrandTemplateDatasetRequest($brand_template_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\Error' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBrandTemplateDatasetAsync
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandTemplateDatasetAsync($brand_template_id, string $contentType = self::contentTypes['getBrandTemplateDataset'][0])
    {
        return $this->getBrandTemplateDatasetAsyncWithHttpInfo($brand_template_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBrandTemplateDatasetAsyncWithHttpInfo
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBrandTemplateDatasetAsyncWithHttpInfo($brand_template_id, string $contentType = self::contentTypes['getBrandTemplateDataset'][0])
    {
        $returnType = '\Integrations\Canva\SDK\Model\GetBrandTemplateDatasetResponse';
        $request = $this->getBrandTemplateDatasetRequest($brand_template_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBrandTemplateDataset'
     *
     * @param  string $brand_template_id The brand template ID. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBrandTemplateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBrandTemplateDatasetRequest($brand_template_id, string $contentType = self::contentTypes['getBrandTemplateDataset'][0])
    {

        // verify the required parameter 'brand_template_id' is set
        if ($brand_template_id === null || (is_array($brand_template_id) && count($brand_template_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $brand_template_id when calling getBrandTemplateDataset'
            );
        }
        if (!preg_match("/^[a-zA-Z0-9_-]{1,50}$/", $brand_template_id)) {
            throw new \InvalidArgumentException("invalid value for \"brand_template_id\" when calling BrandTemplateApi.getBrandTemplateDataset, must conform to the pattern /^[a-zA-Z0-9_-]{1,50}$/.");
        }
        

        $resourcePath = '/v1/brand-templates/{brandTemplateId}/dataset';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($brand_template_id !== null) {
            $resourcePath = str_replace(
                '{' . 'brandTemplateId' . '}',
                ObjectSerializer::toPathValue($brand_template_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listBrandTemplates
     *
     * @param  string $query Lets you search the brand templates available to the user using a search term or terms. (optional)
     * @param  string $continuation If the success response contains a continuation token, the user has access to more brand templates you can list. You can use this token as a query parameter and retrieve more templates from the list, for example &#x60;/v1/brand-templates?continuation&#x3D;{continuation}&#x60;. To retrieve all the brand templates available to the user, you might need to make multiple requests. (optional)
     * @param  OwnershipType $ownership Filter the list of brand templates based on the user&#39;s ownership of the brand templates. This can be one of the following:  - &#x60;any&#x60;: (Default) Brand templates owned by and shared with the user. - &#x60;owned&#x60;: Brand templates owned by the user. - &#x60;shared&#x60;: Brand templates shared with the user. (optional)
     * @param  SortByType $sort_by Sort the list of brand templates. This can be one of the following:  - &#x60;relevance&#x60;: (Default) Sort results using a relevance algorithm. - &#x60;modified_descending&#x60;: Sort results by the date last modified in descending order. - &#x60;modified_ascending&#x60;: Sort results by the date last modified in ascending order. - &#x60;title_descending&#x60;: Sort results by title in descending order. - &#x60;title_ascending&#x60;: Sort results by title in ascending order. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBrandTemplates'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Integrations\Canva\SDK\Model\ListBrandTemplatesResponse|\Integrations\Canva\SDK\Model\Error
     */
    public function listBrandTemplates($query = null, $continuation = null, $ownership = null, $sort_by = null, string $contentType = self::contentTypes['listBrandTemplates'][0])
    {
        list($response) = $this->listBrandTemplatesWithHttpInfo($query, $continuation, $ownership, $sort_by, $contentType);
        return $response;
    }

    /**
     * Operation listBrandTemplatesWithHttpInfo
     *
     * @param  string $query Lets you search the brand templates available to the user using a search term or terms. (optional)
     * @param  string $continuation If the success response contains a continuation token, the user has access to more brand templates you can list. You can use this token as a query parameter and retrieve more templates from the list, for example &#x60;/v1/brand-templates?continuation&#x3D;{continuation}&#x60;. To retrieve all the brand templates available to the user, you might need to make multiple requests. (optional)
     * @param  OwnershipType $ownership Filter the list of brand templates based on the user&#39;s ownership of the brand templates. This can be one of the following:  - &#x60;any&#x60;: (Default) Brand templates owned by and shared with the user. - &#x60;owned&#x60;: Brand templates owned by the user. - &#x60;shared&#x60;: Brand templates shared with the user. (optional)
     * @param  SortByType $sort_by Sort the list of brand templates. This can be one of the following:  - &#x60;relevance&#x60;: (Default) Sort results using a relevance algorithm. - &#x60;modified_descending&#x60;: Sort results by the date last modified in descending order. - &#x60;modified_ascending&#x60;: Sort results by the date last modified in ascending order. - &#x60;title_descending&#x60;: Sort results by title in descending order. - &#x60;title_ascending&#x60;: Sort results by title in ascending order. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBrandTemplates'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Integrations\Canva\SDK\Model\ListBrandTemplatesResponse|\Integrations\Canva\SDK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function listBrandTemplatesWithHttpInfo($query = null, $continuation = null, $ownership = null, $sort_by = null, string $contentType = self::contentTypes['listBrandTemplates'][0])
    {
        $request = $this->listBrandTemplatesRequest($query, $continuation, $ownership, $sort_by, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\Error' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listBrandTemplatesAsync
     *
     * @param  string $query Lets you search the brand templates available to the user using a search term or terms. (optional)
     * @param  string $continuation If the success response contains a continuation token, the user has access to more brand templates you can list. You can use this token as a query parameter and retrieve more templates from the list, for example &#x60;/v1/brand-templates?continuation&#x3D;{continuation}&#x60;. To retrieve all the brand templates available to the user, you might need to make multiple requests. (optional)
     * @param  OwnershipType $ownership Filter the list of brand templates based on the user&#39;s ownership of the brand templates. This can be one of the following:  - &#x60;any&#x60;: (Default) Brand templates owned by and shared with the user. - &#x60;owned&#x60;: Brand templates owned by the user. - &#x60;shared&#x60;: Brand templates shared with the user. (optional)
     * @param  SortByType $sort_by Sort the list of brand templates. This can be one of the following:  - &#x60;relevance&#x60;: (Default) Sort results using a relevance algorithm. - &#x60;modified_descending&#x60;: Sort results by the date last modified in descending order. - &#x60;modified_ascending&#x60;: Sort results by the date last modified in ascending order. - &#x60;title_descending&#x60;: Sort results by title in descending order. - &#x60;title_ascending&#x60;: Sort results by title in ascending order. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBrandTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBrandTemplatesAsync($query = null, $continuation = null, $ownership = null, $sort_by = null, string $contentType = self::contentTypes['listBrandTemplates'][0])
    {
        return $this->listBrandTemplatesAsyncWithHttpInfo($query, $continuation, $ownership, $sort_by, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listBrandTemplatesAsyncWithHttpInfo
     *
     * @param  string $query Lets you search the brand templates available to the user using a search term or terms. (optional)
     * @param  string $continuation If the success response contains a continuation token, the user has access to more brand templates you can list. You can use this token as a query parameter and retrieve more templates from the list, for example &#x60;/v1/brand-templates?continuation&#x3D;{continuation}&#x60;. To retrieve all the brand templates available to the user, you might need to make multiple requests. (optional)
     * @param  OwnershipType $ownership Filter the list of brand templates based on the user&#39;s ownership of the brand templates. This can be one of the following:  - &#x60;any&#x60;: (Default) Brand templates owned by and shared with the user. - &#x60;owned&#x60;: Brand templates owned by the user. - &#x60;shared&#x60;: Brand templates shared with the user. (optional)
     * @param  SortByType $sort_by Sort the list of brand templates. This can be one of the following:  - &#x60;relevance&#x60;: (Default) Sort results using a relevance algorithm. - &#x60;modified_descending&#x60;: Sort results by the date last modified in descending order. - &#x60;modified_ascending&#x60;: Sort results by the date last modified in ascending order. - &#x60;title_descending&#x60;: Sort results by title in descending order. - &#x60;title_ascending&#x60;: Sort results by title in ascending order. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBrandTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBrandTemplatesAsyncWithHttpInfo($query = null, $continuation = null, $ownership = null, $sort_by = null, string $contentType = self::contentTypes['listBrandTemplates'][0])
    {
        $returnType = '\Integrations\Canva\SDK\Model\ListBrandTemplatesResponse';
        $request = $this->listBrandTemplatesRequest($query, $continuation, $ownership, $sort_by, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listBrandTemplates'
     *
     * @param  string $query Lets you search the brand templates available to the user using a search term or terms. (optional)
     * @param  string $continuation If the success response contains a continuation token, the user has access to more brand templates you can list. You can use this token as a query parameter and retrieve more templates from the list, for example &#x60;/v1/brand-templates?continuation&#x3D;{continuation}&#x60;. To retrieve all the brand templates available to the user, you might need to make multiple requests. (optional)
     * @param  OwnershipType $ownership Filter the list of brand templates based on the user&#39;s ownership of the brand templates. This can be one of the following:  - &#x60;any&#x60;: (Default) Brand templates owned by and shared with the user. - &#x60;owned&#x60;: Brand templates owned by the user. - &#x60;shared&#x60;: Brand templates shared with the user. (optional)
     * @param  SortByType $sort_by Sort the list of brand templates. This can be one of the following:  - &#x60;relevance&#x60;: (Default) Sort results using a relevance algorithm. - &#x60;modified_descending&#x60;: Sort results by the date last modified in descending order. - &#x60;modified_ascending&#x60;: Sort results by the date last modified in ascending order. - &#x60;title_descending&#x60;: Sort results by title in descending order. - &#x60;title_ascending&#x60;: Sort results by title in ascending order. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBrandTemplates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listBrandTemplatesRequest($query = null, $continuation = null, $ownership = null, $sort_by = null, string $contentType = self::contentTypes['listBrandTemplates'][0])
    {






        $resourcePath = '/v1/brand-templates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $continuation,
            'continuation', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ownership,
            'ownership', // param base name
            'OwnershipType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'SortByType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
