<?php
/**
 * OauthApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Integrations\Canva\SDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Integrations\Canva\SDK\ApiException;
use Integrations\Canva\SDK\Configuration;
use Integrations\Canva\SDK\HeaderSelector;
use Integrations\Canva\SDK\ObjectSerializer;

/**
 * OauthApi Class Doc Comment
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OauthApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'exchangeAccessToken' => [
            'application/x-www-form-urlencoded',
        ],
        'introspectToken' => [
            'application/x-www-form-urlencoded',
        ],
        'revokeTokens' => [
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation exchangeAccessToken
     *
     * @param  string $grant_type For generating an access token using a refresh token. (optional)
     * @param  string $code_verifier The &#x60;code_verifier&#x60; value that you generated when creating the user authorization URL. (optional)
     * @param  string $code The authorization code you received after the user authorized the integration. (optional)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $redirect_uri Only required if a redirect URL was supplied when you [created the user authorization URL](https://www.canva.dev/docs/connect/authentication/#create-the-authorization-url).  Must be one of those already specified by the client. If not supplied, the first redirect_uri defined for the client will be used by default. (optional)
     * @param  string $refresh_token The refresh token to be exchanged. You can copy this value from the successful response received when generating an access token. (optional)
     * @param  string $scope Optional scope value when refreshing an access token. Separate multiple [scopes](https://www.canva.dev/docs/connect/appendix/scopes/) with a single space between each scope.  The requested scope cannot include any permissions not already granted, so this parameter allows you to limit the scope when refreshing a token. If omitted, the scope for the token remains unchanged. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeAccessToken'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse|\Integrations\Canva\SDK\Model\OauthError
     */
    public function exchangeAccessToken($grant_type = null, $code_verifier = null, $code = null, $client_id = null, $client_secret = null, $redirect_uri = null, $refresh_token = null, $scope = null, string $contentType = self::contentTypes['exchangeAccessToken'][0])
    {
        list($response) = $this->exchangeAccessTokenWithHttpInfo($grant_type, $code_verifier, $code, $client_id, $client_secret, $redirect_uri, $refresh_token, $scope, $contentType);
        return $response;
    }

    /**
     * Operation exchangeAccessTokenWithHttpInfo
     *
     * @param  string $grant_type For generating an access token using a refresh token. (optional)
     * @param  string $code_verifier The &#x60;code_verifier&#x60; value that you generated when creating the user authorization URL. (optional)
     * @param  string $code The authorization code you received after the user authorized the integration. (optional)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $redirect_uri Only required if a redirect URL was supplied when you [created the user authorization URL](https://www.canva.dev/docs/connect/authentication/#create-the-authorization-url).  Must be one of those already specified by the client. If not supplied, the first redirect_uri defined for the client will be used by default. (optional)
     * @param  string $refresh_token The refresh token to be exchanged. You can copy this value from the successful response received when generating an access token. (optional)
     * @param  string $scope Optional scope value when refreshing an access token. Separate multiple [scopes](https://www.canva.dev/docs/connect/appendix/scopes/) with a single space between each scope.  The requested scope cannot include any permissions not already granted, so this parameter allows you to limit the scope when refreshing a token. If omitted, the scope for the token remains unchanged. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeAccessToken'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse|\Integrations\Canva\SDK\Model\OauthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function exchangeAccessTokenWithHttpInfo($grant_type = null, $code_verifier = null, $code = null, $client_id = null, $client_secret = null, $redirect_uri = null, $refresh_token = null, $scope = null, string $contentType = self::contentTypes['exchangeAccessToken'][0])
    {
        $request = $this->exchangeAccessTokenRequest($grant_type, $code_verifier, $code, $client_id, $client_secret, $redirect_uri, $refresh_token, $scope, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\OauthError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\OauthError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\OauthError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation exchangeAccessTokenAsync
     *
     * @param  string $grant_type For generating an access token using a refresh token. (optional)
     * @param  string $code_verifier The &#x60;code_verifier&#x60; value that you generated when creating the user authorization URL. (optional)
     * @param  string $code The authorization code you received after the user authorized the integration. (optional)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $redirect_uri Only required if a redirect URL was supplied when you [created the user authorization URL](https://www.canva.dev/docs/connect/authentication/#create-the-authorization-url).  Must be one of those already specified by the client. If not supplied, the first redirect_uri defined for the client will be used by default. (optional)
     * @param  string $refresh_token The refresh token to be exchanged. You can copy this value from the successful response received when generating an access token. (optional)
     * @param  string $scope Optional scope value when refreshing an access token. Separate multiple [scopes](https://www.canva.dev/docs/connect/appendix/scopes/) with a single space between each scope.  The requested scope cannot include any permissions not already granted, so this parameter allows you to limit the scope when refreshing a token. If omitted, the scope for the token remains unchanged. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeAccessToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exchangeAccessTokenAsync($grant_type = null, $code_verifier = null, $code = null, $client_id = null, $client_secret = null, $redirect_uri = null, $refresh_token = null, $scope = null, string $contentType = self::contentTypes['exchangeAccessToken'][0])
    {
        return $this->exchangeAccessTokenAsyncWithHttpInfo($grant_type, $code_verifier, $code, $client_id, $client_secret, $redirect_uri, $refresh_token, $scope, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation exchangeAccessTokenAsyncWithHttpInfo
     *
     * @param  string $grant_type For generating an access token using a refresh token. (optional)
     * @param  string $code_verifier The &#x60;code_verifier&#x60; value that you generated when creating the user authorization URL. (optional)
     * @param  string $code The authorization code you received after the user authorized the integration. (optional)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $redirect_uri Only required if a redirect URL was supplied when you [created the user authorization URL](https://www.canva.dev/docs/connect/authentication/#create-the-authorization-url).  Must be one of those already specified by the client. If not supplied, the first redirect_uri defined for the client will be used by default. (optional)
     * @param  string $refresh_token The refresh token to be exchanged. You can copy this value from the successful response received when generating an access token. (optional)
     * @param  string $scope Optional scope value when refreshing an access token. Separate multiple [scopes](https://www.canva.dev/docs/connect/appendix/scopes/) with a single space between each scope.  The requested scope cannot include any permissions not already granted, so this parameter allows you to limit the scope when refreshing a token. If omitted, the scope for the token remains unchanged. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeAccessToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exchangeAccessTokenAsyncWithHttpInfo($grant_type = null, $code_verifier = null, $code = null, $client_id = null, $client_secret = null, $redirect_uri = null, $refresh_token = null, $scope = null, string $contentType = self::contentTypes['exchangeAccessToken'][0])
    {
        $returnType = '\Integrations\Canva\SDK\Model\ExchangeAccessTokenResponse';
        $request = $this->exchangeAccessTokenRequest($grant_type, $code_verifier, $code, $client_id, $client_secret, $redirect_uri, $refresh_token, $scope, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'exchangeAccessToken'
     *
     * @param  string $grant_type For generating an access token using a refresh token. (optional)
     * @param  string $code_verifier The &#x60;code_verifier&#x60; value that you generated when creating the user authorization URL. (optional)
     * @param  string $code The authorization code you received after the user authorized the integration. (optional)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $redirect_uri Only required if a redirect URL was supplied when you [created the user authorization URL](https://www.canva.dev/docs/connect/authentication/#create-the-authorization-url).  Must be one of those already specified by the client. If not supplied, the first redirect_uri defined for the client will be used by default. (optional)
     * @param  string $refresh_token The refresh token to be exchanged. You can copy this value from the successful response received when generating an access token. (optional)
     * @param  string $scope Optional scope value when refreshing an access token. Separate multiple [scopes](https://www.canva.dev/docs/connect/appendix/scopes/) with a single space between each scope.  The requested scope cannot include any permissions not already granted, so this parameter allows you to limit the scope when refreshing a token. If omitted, the scope for the token remains unchanged. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exchangeAccessToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function exchangeAccessTokenRequest($grant_type = null, $code_verifier = null, $code = null, $client_id = null, $client_secret = null, $redirect_uri = null, $refresh_token = null, $scope = null, string $contentType = self::contentTypes['exchangeAccessToken'][0])
    {










        $resourcePath = '/v1/oauth/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($grant_type !== null) {
            $formParams['grant_type'] = ObjectSerializer::toFormValue($grant_type);
        }
        // form params
        if ($code_verifier !== null) {
            $formParams['code_verifier'] = ObjectSerializer::toFormValue($code_verifier);
        }
        // form params
        if ($code !== null) {
            $formParams['code'] = ObjectSerializer::toFormValue($code);
        }
        // form params
        if ($client_id !== null) {
            $formParams['client_id'] = ObjectSerializer::toFormValue($client_id);
        }
        // form params
        if ($client_secret !== null) {
            $formParams['client_secret'] = ObjectSerializer::toFormValue($client_secret);
        }
        // form params
        if ($redirect_uri !== null) {
            $formParams['redirect_uri'] = ObjectSerializer::toFormValue($redirect_uri);
        }
        // form params
        if ($refresh_token !== null) {
            $formParams['refresh_token'] = ObjectSerializer::toFormValue($refresh_token);
        }
        // form params
        if ($scope !== null) {
            $formParams['scope'] = ObjectSerializer::toFormValue($scope);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation introspectToken
     *
     * @param  string $token The token to introspect. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Integrations\Canva\SDK\Model\IntrospectTokenResponse|\Integrations\Canva\SDK\Model\OauthError
     */
    public function introspectToken($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        list($response) = $this->introspectTokenWithHttpInfo($token, $client_id, $client_secret, $contentType);
        return $response;
    }

    /**
     * Operation introspectTokenWithHttpInfo
     *
     * @param  string $token The token to introspect. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Integrations\Canva\SDK\Model\IntrospectTokenResponse|\Integrations\Canva\SDK\Model\OauthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function introspectTokenWithHttpInfo($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        $request = $this->introspectTokenRequest($token, $client_id, $client_secret, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Integrations\Canva\SDK\Model\IntrospectTokenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\IntrospectTokenResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\IntrospectTokenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\OauthError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\OauthError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\OauthError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Integrations\Canva\SDK\Model\IntrospectTokenResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\IntrospectTokenResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation introspectTokenAsync
     *
     * @param  string $token The token to introspect. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function introspectTokenAsync($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        return $this->introspectTokenAsyncWithHttpInfo($token, $client_id, $client_secret, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation introspectTokenAsyncWithHttpInfo
     *
     * @param  string $token The token to introspect. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function introspectTokenAsyncWithHttpInfo($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['introspectToken'][0])
    {
        $returnType = '\Integrations\Canva\SDK\Model\IntrospectTokenResponse';
        $request = $this->introspectTokenRequest($token, $client_id, $client_secret, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'introspectToken'
     *
     * @param  string $token The token to introspect. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['introspectToken'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function introspectTokenRequest($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['introspectToken'][0])
    {

        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling introspectToken'
            );
        }




        $resourcePath = '/v1/oauth/introspect';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($token !== null) {
            $formParams['token'] = ObjectSerializer::toFormValue($token);
        }
        // form params
        if ($client_id !== null) {
            $formParams['client_id'] = ObjectSerializer::toFormValue($client_id);
        }
        // form params
        if ($client_secret !== null) {
            $formParams['client_secret'] = ObjectSerializer::toFormValue($client_secret);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation revokeTokens
     *
     * @param  string $token The token to revoke. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeTokens'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Integrations\Canva\SDK\Model\OauthError
     */
    public function revokeTokens($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['revokeTokens'][0])
    {
        list($response) = $this->revokeTokensWithHttpInfo($token, $client_id, $client_secret, $contentType);
        return $response;
    }

    /**
     * Operation revokeTokensWithHttpInfo
     *
     * @param  string $token The token to revoke. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeTokens'] to see the possible values for this operation
     *
     * @throws \Integrations\Canva\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Integrations\Canva\SDK\Model\OauthError, HTTP status code, HTTP response headers (array of strings)
     */
    public function revokeTokensWithHttpInfo($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['revokeTokens'][0])
    {
        $request = $this->revokeTokensRequest($token, $client_id, $client_secret, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\Integrations\Canva\SDK\Model\OauthError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Integrations\Canva\SDK\Model\OauthError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Integrations\Canva\SDK\Model\OauthError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Integrations\Canva\SDK\Model\OauthError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation revokeTokensAsync
     *
     * @param  string $token The token to revoke. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeTokens'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revokeTokensAsync($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['revokeTokens'][0])
    {
        return $this->revokeTokensAsyncWithHttpInfo($token, $client_id, $client_secret, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation revokeTokensAsyncWithHttpInfo
     *
     * @param  string $token The token to revoke. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeTokens'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function revokeTokensAsyncWithHttpInfo($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['revokeTokens'][0])
    {
        $returnType = 'object';
        $request = $this->revokeTokensRequest($token, $client_id, $client_secret, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'revokeTokens'
     *
     * @param  string $token The token to revoke. (required)
     * @param  string $client_id Your integration&#39;s unique ID, for authenticating the request.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $client_secret Your integration&#39;s client secret, for authenticating the request. Begins with &#x60;cnvca&#x60;.  NOTE: We recommend that you use basic access authentication instead of specifying &#x60;client_id&#x60; and &#x60;client_secret&#x60; as body parameters. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['revokeTokens'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function revokeTokensRequest($token, $client_id = null, $client_secret = null, string $contentType = self::contentTypes['revokeTokens'][0])
    {

        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling revokeTokens'
            );
        }




        $resourcePath = '/v1/oauth/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($token !== null) {
            $formParams['token'] = ObjectSerializer::toFormValue($token);
        }
        // form params
        if ($client_id !== null) {
            $formParams['client_id'] = ObjectSerializer::toFormValue($client_id);
        }
        // form params
        if ($client_secret !== null) {
            $formParams['client_secret'] = ObjectSerializer::toFormValue($client_secret);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
