<?php
/**
 * DesignImportErrorCode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Integrations\Canva\SDK\Model;
use \Integrations\Canva\SDK\ObjectSerializer;

/**
 * DesignImportErrorCode Class Doc Comment
 *
 * @category Class
 * @description A short string about why the import failed. You can programmatically handle errors using this field.
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignImportErrorCode
{
    /**
     * Possible values of this enum
     */
    public const DESIGN_CREATION_THROTTLED = 'design_creation_throttled';

    public const DESIGN_IMPORT_THROTTLED = 'design_import_throttled';

    public const DUPLICATE_IMPORT = 'duplicate_import';

    public const INTERNAL_SERVER_ERROR = 'internal_server_error';

    public const INVALID_FILE = 'invalid_file';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESIGN_CREATION_THROTTLED,
            self::DESIGN_IMPORT_THROTTLED,
            self::DUPLICATE_IMPORT,
            self::INTERNAL_SERVER_ERROR,
            self::INVALID_FILE
        ];
    }
}


