<?php
/**
 * NotificationContent
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Integrations\Canva\SDK\Model;

use \ArrayAccess;
use \Integrations\Canva\SDK\ObjectSerializer;

/**
 * NotificationContent Class Doc Comment
 *
 * @category Class
 * @description The notification content object, which contains metadata about the event.
 * @package  Integrations\Canva\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NotificationContent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NotificationContent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'triggering_user' => '\Integrations\Canva\SDK\Model\TeamUser',
        'receiving_team_user' => '\Integrations\Canva\SDK\Model\TeamUser',
        'design' => '\Integrations\Canva\SDK\Model\DesignSummary',
        'share' => '\Integrations\Canva\SDK\Model\ShareAction',
        'folder' => '\Integrations\Canva\SDK\Model\Folder',
        'comment' => '\Integrations\Canva\SDK\Model\CommentEvent',
        'requested_groups' => '\Integrations\Canva\SDK\Model\Group[]',
        'approval_request' => '\Integrations\Canva\SDK\Model\ApprovalRequestAction',
        'requesting_user' => '\Integrations\Canva\SDK\Model\User',
        'responding_groups' => '\Integrations\Canva\SDK\Model\Group[]',
        'approval_response' => '\Integrations\Canva\SDK\Model\ApprovalResponseAction',
        'receiving_user' => '\Integrations\Canva\SDK\Model\User',
        'inviting_team' => '\Integrations\Canva\SDK\Model\Team'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'triggering_user' => null,
        'receiving_team_user' => null,
        'design' => null,
        'share' => null,
        'folder' => null,
        'comment' => null,
        'requested_groups' => null,
        'approval_request' => null,
        'requesting_user' => null,
        'responding_groups' => null,
        'approval_response' => null,
        'receiving_user' => null,
        'inviting_team' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'triggering_user' => false,
        'receiving_team_user' => false,
        'design' => false,
        'share' => false,
        'folder' => false,
        'comment' => false,
        'requested_groups' => false,
        'approval_request' => false,
        'requesting_user' => false,
        'responding_groups' => false,
        'approval_response' => false,
        'receiving_user' => false,
        'inviting_team' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'triggering_user' => 'triggering_user',
        'receiving_team_user' => 'receiving_team_user',
        'design' => 'design',
        'share' => 'share',
        'folder' => 'folder',
        'comment' => 'comment',
        'requested_groups' => 'requested_groups',
        'approval_request' => 'approval_request',
        'requesting_user' => 'requesting_user',
        'responding_groups' => 'responding_groups',
        'approval_response' => 'approval_response',
        'receiving_user' => 'receiving_user',
        'inviting_team' => 'inviting_team'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'triggering_user' => 'setTriggeringUser',
        'receiving_team_user' => 'setReceivingTeamUser',
        'design' => 'setDesign',
        'share' => 'setShare',
        'folder' => 'setFolder',
        'comment' => 'setComment',
        'requested_groups' => 'setRequestedGroups',
        'approval_request' => 'setApprovalRequest',
        'requesting_user' => 'setRequestingUser',
        'responding_groups' => 'setRespondingGroups',
        'approval_response' => 'setApprovalResponse',
        'receiving_user' => 'setReceivingUser',
        'inviting_team' => 'setInvitingTeam'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'triggering_user' => 'getTriggeringUser',
        'receiving_team_user' => 'getReceivingTeamUser',
        'design' => 'getDesign',
        'share' => 'getShare',
        'folder' => 'getFolder',
        'comment' => 'getComment',
        'requested_groups' => 'getRequestedGroups',
        'approval_request' => 'getApprovalRequest',
        'requesting_user' => 'getRequestingUser',
        'responding_groups' => 'getRespondingGroups',
        'approval_response' => 'getApprovalResponse',
        'receiving_user' => 'getReceivingUser',
        'inviting_team' => 'getInvitingTeam'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_SHARE_DESIGN = 'share_design';
    public const TYPE_SHARE_FOLDER = 'share_folder';
    public const TYPE_COMMENT = 'comment';
    public const TYPE_DESIGN_ACCESS_REQUESTED = 'design_access_requested';
    public const TYPE_DESIGN_APPROVAL_REQUESTED = 'design_approval_requested';
    public const TYPE_DESIGN_APPROVAL_RESPONSE = 'design_approval_response';
    public const TYPE_DESIGN_APPROVAL_REVIEWER_INVALIDATED = 'design_approval_reviewer_invalidated';
    public const TYPE_DESIGN_MENTION = 'design_mention';
    public const TYPE_TEAM_INVITE = 'team_invite';
    public const TYPE_FOLDER_ACCESS_REQUESTED = 'folder_access_requested';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SHARE_DESIGN,
            self::TYPE_SHARE_FOLDER,
            self::TYPE_COMMENT,
            self::TYPE_DESIGN_ACCESS_REQUESTED,
            self::TYPE_DESIGN_APPROVAL_REQUESTED,
            self::TYPE_DESIGN_APPROVAL_RESPONSE,
            self::TYPE_DESIGN_APPROVAL_REVIEWER_INVALIDATED,
            self::TYPE_DESIGN_MENTION,
            self::TYPE_TEAM_INVITE,
            self::TYPE_FOLDER_ACCESS_REQUESTED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('triggering_user', $data ?? [], null);
        $this->setIfExists('receiving_team_user', $data ?? [], null);
        $this->setIfExists('design', $data ?? [], null);
        $this->setIfExists('share', $data ?? [], null);
        $this->setIfExists('folder', $data ?? [], null);
        $this->setIfExists('comment', $data ?? [], null);
        $this->setIfExists('requested_groups', $data ?? [], null);
        $this->setIfExists('approval_request', $data ?? [], null);
        $this->setIfExists('requesting_user', $data ?? [], null);
        $this->setIfExists('responding_groups', $data ?? [], null);
        $this->setIfExists('approval_response', $data ?? [], null);
        $this->setIfExists('receiving_user', $data ?? [], null);
        $this->setIfExists('inviting_team', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['triggering_user'] === null) {
            $invalidProperties[] = "'triggering_user' can't be null";
        }
        if ($this->container['receiving_team_user'] === null) {
            $invalidProperties[] = "'receiving_team_user' can't be null";
        }
        if ($this->container['design'] === null) {
            $invalidProperties[] = "'design' can't be null";
        }
        if ($this->container['folder'] === null) {
            $invalidProperties[] = "'folder' can't be null";
        }
        if ($this->container['comment'] === null) {
            $invalidProperties[] = "'comment' can't be null";
        }
        if ($this->container['requested_groups'] === null) {
            $invalidProperties[] = "'requested_groups' can't be null";
        }
        if ($this->container['approval_request'] === null) {
            $invalidProperties[] = "'approval_request' can't be null";
        }
        if ($this->container['responding_groups'] === null) {
            $invalidProperties[] = "'responding_groups' can't be null";
        }
        if ($this->container['approval_response'] === null) {
            $invalidProperties[] = "'approval_response' can't be null";
        }
        if ($this->container['receiving_user'] === null) {
            $invalidProperties[] = "'receiving_user' can't be null";
        }
        if ($this->container['inviting_team'] === null) {
            $invalidProperties[] = "'inviting_team' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets triggering_user
     *
     * @return \Integrations\Canva\SDK\Model\TeamUser
     */
    public function getTriggeringUser()
    {
        return $this->container['triggering_user'];
    }

    /**
     * Sets triggering_user
     *
     * @param \Integrations\Canva\SDK\Model\TeamUser $triggering_user triggering_user
     *
     * @return self
     */
    public function setTriggeringUser($triggering_user)
    {
        if (is_null($triggering_user)) {
            throw new \InvalidArgumentException('non-nullable triggering_user cannot be null');
        }
        $this->container['triggering_user'] = $triggering_user;

        return $this;
    }

    /**
     * Gets receiving_team_user
     *
     * @return \Integrations\Canva\SDK\Model\TeamUser
     */
    public function getReceivingTeamUser()
    {
        return $this->container['receiving_team_user'];
    }

    /**
     * Sets receiving_team_user
     *
     * @param \Integrations\Canva\SDK\Model\TeamUser $receiving_team_user receiving_team_user
     *
     * @return self
     */
    public function setReceivingTeamUser($receiving_team_user)
    {
        if (is_null($receiving_team_user)) {
            throw new \InvalidArgumentException('non-nullable receiving_team_user cannot be null');
        }
        $this->container['receiving_team_user'] = $receiving_team_user;

        return $this;
    }

    /**
     * Gets design
     *
     * @return \Integrations\Canva\SDK\Model\DesignSummary
     */
    public function getDesign()
    {
        return $this->container['design'];
    }

    /**
     * Sets design
     *
     * @param \Integrations\Canva\SDK\Model\DesignSummary $design design
     *
     * @return self
     */
    public function setDesign($design)
    {
        if (is_null($design)) {
            throw new \InvalidArgumentException('non-nullable design cannot be null');
        }
        $this->container['design'] = $design;

        return $this;
    }

    /**
     * Gets share
     *
     * @return \Integrations\Canva\SDK\Model\ShareAction|null
     */
    public function getShare()
    {
        return $this->container['share'];
    }

    /**
     * Sets share
     *
     * @param \Integrations\Canva\SDK\Model\ShareAction|null $share share
     *
     * @return self
     */
    public function setShare($share)
    {
        if (is_null($share)) {
            throw new \InvalidArgumentException('non-nullable share cannot be null');
        }
        $this->container['share'] = $share;

        return $this;
    }

    /**
     * Gets folder
     *
     * @return \Integrations\Canva\SDK\Model\Folder
     */
    public function getFolder()
    {
        return $this->container['folder'];
    }

    /**
     * Sets folder
     *
     * @param \Integrations\Canva\SDK\Model\Folder $folder folder
     *
     * @return self
     */
    public function setFolder($folder)
    {
        if (is_null($folder)) {
            throw new \InvalidArgumentException('non-nullable folder cannot be null');
        }
        $this->container['folder'] = $folder;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return \Integrations\Canva\SDK\Model\CommentEvent
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param \Integrations\Canva\SDK\Model\CommentEvent $comment comment
     *
     * @return self
     */
    public function setComment($comment)
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets requested_groups
     *
     * @return \Integrations\Canva\SDK\Model\Group[]
     */
    public function getRequestedGroups()
    {
        return $this->container['requested_groups'];
    }

    /**
     * Sets requested_groups
     *
     * @param \Integrations\Canva\SDK\Model\Group[] $requested_groups requested_groups
     *
     * @return self
     */
    public function setRequestedGroups($requested_groups)
    {
        if (is_null($requested_groups)) {
            throw new \InvalidArgumentException('non-nullable requested_groups cannot be null');
        }
        $this->container['requested_groups'] = $requested_groups;

        return $this;
    }

    /**
     * Gets approval_request
     *
     * @return \Integrations\Canva\SDK\Model\ApprovalRequestAction
     */
    public function getApprovalRequest()
    {
        return $this->container['approval_request'];
    }

    /**
     * Sets approval_request
     *
     * @param \Integrations\Canva\SDK\Model\ApprovalRequestAction $approval_request approval_request
     *
     * @return self
     */
    public function setApprovalRequest($approval_request)
    {
        if (is_null($approval_request)) {
            throw new \InvalidArgumentException('non-nullable approval_request cannot be null');
        }
        $this->container['approval_request'] = $approval_request;

        return $this;
    }

    /**
     * Gets requesting_user
     *
     * @return \Integrations\Canva\SDK\Model\User|null
     */
    public function getRequestingUser()
    {
        return $this->container['requesting_user'];
    }

    /**
     * Sets requesting_user
     *
     * @param \Integrations\Canva\SDK\Model\User|null $requesting_user requesting_user
     *
     * @return self
     */
    public function setRequestingUser($requesting_user)
    {
        if (is_null($requesting_user)) {
            throw new \InvalidArgumentException('non-nullable requesting_user cannot be null');
        }
        $this->container['requesting_user'] = $requesting_user;

        return $this;
    }

    /**
     * Gets responding_groups
     *
     * @return \Integrations\Canva\SDK\Model\Group[]
     */
    public function getRespondingGroups()
    {
        return $this->container['responding_groups'];
    }

    /**
     * Sets responding_groups
     *
     * @param \Integrations\Canva\SDK\Model\Group[] $responding_groups responding_groups
     *
     * @return self
     */
    public function setRespondingGroups($responding_groups)
    {
        if (is_null($responding_groups)) {
            throw new \InvalidArgumentException('non-nullable responding_groups cannot be null');
        }
        $this->container['responding_groups'] = $responding_groups;

        return $this;
    }

    /**
     * Gets approval_response
     *
     * @return \Integrations\Canva\SDK\Model\ApprovalResponseAction
     */
    public function getApprovalResponse()
    {
        return $this->container['approval_response'];
    }

    /**
     * Sets approval_response
     *
     * @param \Integrations\Canva\SDK\Model\ApprovalResponseAction $approval_response approval_response
     *
     * @return self
     */
    public function setApprovalResponse($approval_response)
    {
        if (is_null($approval_response)) {
            throw new \InvalidArgumentException('non-nullable approval_response cannot be null');
        }
        $this->container['approval_response'] = $approval_response;

        return $this;
    }

    /**
     * Gets receiving_user
     *
     * @return \Integrations\Canva\SDK\Model\User
     */
    public function getReceivingUser()
    {
        return $this->container['receiving_user'];
    }

    /**
     * Sets receiving_user
     *
     * @param \Integrations\Canva\SDK\Model\User $receiving_user receiving_user
     *
     * @return self
     */
    public function setReceivingUser($receiving_user)
    {
        if (is_null($receiving_user)) {
            throw new \InvalidArgumentException('non-nullable receiving_user cannot be null');
        }
        $this->container['receiving_user'] = $receiving_user;

        return $this;
    }

    /**
     * Gets inviting_team
     *
     * @return \Integrations\Canva\SDK\Model\Team
     */
    public function getInvitingTeam()
    {
        return $this->container['inviting_team'];
    }

    /**
     * Sets inviting_team
     *
     * @param \Integrations\Canva\SDK\Model\Team $inviting_team inviting_team
     *
     * @return self
     */
    public function setInvitingTeam($inviting_team)
    {
        if (is_null($inviting_team)) {
            throw new \InvalidArgumentException('non-nullable inviting_team cannot be null');
        }
        $this->container['inviting_team'] = $inviting_team;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


