<?php
/**
 * ExportErrorCodeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ExportErrorCodeTest Class Doc Comment
 *
 * @category    Class
 * @description If the export failed, this specifies the reason why it failed. This can be one of the following:  - &#x60;license_required&#x60;: The design contains [premium elements](https://www.canva.com/help/premium-elements/) that haven&#39;t been purchased. You can either buy the elements or upgrade to a Canva plan (such as Canva Pro) that has premium features, then try again. Alternatively, you can set &#x60;export_quality&#x60; to &#x60;regular&#x60; to export your document in regular quality. - &#x60;internal_failure&#x60;: The service encountered an error when exporting your design.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExportErrorCodeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExportErrorCode"
     */
    public function testExportErrorCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
