<?php
/**
 * PresetDesignTypeNameTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Canva Connect API
 *
 * API for building integrations with Canva via a REST api
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PresetDesignTypeNameTest Class Doc Comment
 *
 * @category    Class
 * @description The name of the design type. This can be one of the following:  - &#x60;doc&#x60;: A [Canva doc](https://www.canva.com/docs/); a document for Canva&#39;s online text editor. - &#x60;whiteboard&#x60;: A [whiteboard](https://www.canva.com/online-whiteboard/); a design which gives you infinite space to collaborate. - &#x60;presentation&#x60;: A [presentation](https://www.canva.com/presentations/); lets you create and collaborate for presenting to an audience.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PresetDesignTypeNameTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PresetDesignTypeName"
     */
    public function testPresetDesignTypeName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
